package com.ek.graphql.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

import jakarta.persistence.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "t_customer")
public class Customer {
	
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "customer_id")
    private Long customerId;

    @Column(name = "customer_name")
    private String customerName;

    @Column(name = "customer_code")
    private String customerCode;

    @Column(name = "customer_address")
    private String customerAddress;

    @Column(name = "customer_amount")
    private Long customerAmount;

    @Column(name = "customer_type")
    private Long customerType;
    
    @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL)
    List<Inventory> inventories;

	public void setInventories(List<Inventory> inventories) {
		this.inventories = inventories;
	}
	public List<Inventory> getInventories() {
		return this.inventories;
	}
    // Getter and setter methods are automatically generated by Lombok.
}