package com.ek.graphql.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import jakarta.persistence.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "t_inventory")
public class Inventory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "inventory_id")
    private Long inventoryId;

    @Column(name = "inventory_name")
    private String inventoryName;

    @Column(name = "inventory_code")
    private String inventoryCode;

    @Column(name = "inventory_amount")
    private Long inventoryAmount;

    @Column(name = "inventory_type")
    private Long inventoryType;

    @Column(name = "inventory_price")
    private Long inventoryPrice;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private Customer customer;
    
    // Getter and setter methods are automatically generated by Lombok.
}
